# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

users = User.create([{ :email => "admin@example.com", :password => "adminadmin", :password_confirmation => "adminadmin", :role => "admin" },
                      { :email => "user@example.com", :password => "useruser", :password_confirmation => "useruser", :role => "user" },
                      { :email => "teacher@example.com", :password => "teacherteacher", :password_confirmation => "teacherteacher", :role => "teacher" }])
  
categories = Category.create([{ name: "3D + Animation" }, 
                              { name: "Audio" },
                              { name: "Business" },
                              { name: "Design" },
                              { name: "Developer" },
                              { name: "Home Computing" },
                              { name: "Photography" },
                              { name: "Video" },
                              { name: "Web + Interactive" }])

courses = Course.create([{ name: "Nuke 6 New Features", description: "Author Steve Wright explores the new features found in the 3D digital compositor Nuke 6. The course introduces the RotoPaint node for drawing and painting effects, the Keylight keyer for creating mattes and composites, and the SplineWarp node for warping images. The course also explains how to merge keys, animate with keyframes, and create image-based blurs. Exercise files accompany the course.

Nuke 6 New Features was created and produced by Steve Wright. We are honored to host his material in the lynda.com Online Training Library" },
                        { category_id: 1,name: "CINEMA 4D R13 New Features", description: "This course spotlights the R13 update for MAXON CINEMA 4D, which includes some key improvements in the rendering, shader, and character tools. Author Rob Garrott shows animators how to find their way around the interface, and demonstrates features such as the Physical Render engine, with its camera and depth of field and motion blur controls; the CMotion system for creating parametric movement; and the new and revised shaders. The course also covers the streamlined workflow for Adobe After Effects Exchange and the new file format options OpenEXR and Xref. Exercise files are included with the course." },
                        { category_id: 1,name: "Digital Creature Creation in ZBrush, Photoshop, and Maya", description: "Author Ryan Kittleson introduces the skills digital artists need to create photorealistic 3D creatures for film, video, and game production. The course covers basic design, sculpting, texturing, posing, and lighting and demonstrates real-world workflow, starting with the basic sculpture in ZBrush and moving it into Maya for finishing, while editing textures in Photoshop." },
                        { category_id: 1,name: "Revit Architecture: Rendering", description: "This course offers an in-depth look at the rendering features of Revit, including photometric lighting, sun, and exposure and its basic animation tools. Author Paul F. Aubin covers creating 3D views; modeling wall layers, sweeps, and custom components; applying materials and custom textures to objects; and rendering the final scene with optimal quality settings. The course also shows how to create a walk-through that showcases designs. Exercise files are included with the course." },
                        { category_id: 1,name: "Photoshop CS5 Extended One-on-One: 3D Type Effects", description: "In this final installment of Photoshop CS5 Extended One-on-One, Deke McClelland creates a total of seven 3D type effects from scratch. This project-based course shows how to create and modify 3D type, craft hand-drawn effects, and design complex character extrusions. The course also explains how to color-correct and post-process 3D type in Camera RAW. Exercise files accompany the course." },
                        { category_id: 1,name: "mocha Essential Training", description: "mocha has always been very popular as a tracking tool, but with the rising interest in stereo 3D conversion, its rotoscoping capabilities have become a favorite player in that pipeline and sales have soared. mocha Essential Training with Steve Wright covers the basics of operating mocha, as well as advanced tracking and rotoscoping techniques. The course also covers the mocha/Nuke stereo 3D production pipeline in detail. Exercise files are included with the course." },
                        { category_id: 1,name: "Revit Architecture: The Family Editor", description: "In this course, Paul F. Aubin creates standardized content such as furniture, doors, and many other architectural components using The Family Editor in Revit. The course starts with the basic concepts: family hierarchy, libraries, resources, reference planes, and constraints. The course also takes a deeper look at the smart data beyond the geometry, such as material and visibility parameters, as well as creating nested families and arrays, controlling rotation in work planes, and working with advanced formulas. Exercise files are included with the course." },
                        { category_id: 1,name: "modo 501 Essential Training", description: "In this course, author Dan Ablan walks through the process of understanding the modo workflow while learning to create 3D models and animations. The course teaches fundamental tasks, such as modeling polygons and applying materials with the Shader Tree, while exploring scene building in depth through advanced lighting, camera, and animation techniques. The course also covers modo's schematic tools and shows how to render animations for various playback media. Exercise files accompany the course." },
                        { category_id: 1,name: "Branden Hall: Interactive Architect and Digital Maker", description: "This course introduces Branden Hall, a software architect and programmer, who has spent well over a decade pushing the limits of the web, and teaching others how to do the same. The cofounder and CEO of Automata Studios, Branden is an acknowledged expert in the field of interactive media, producing award-winning work and authoring books that serve as touchstones for the design community.

Branden opens up his personal studio and explains his fascination with making whether through programming or woodwork, and the magic behind bringing his ideas to life. Branden and crew also visit the BLOOM installation, a project designed to display artwork for La Plaza de Cultura y Artes, a museum dedicated to Mexican American history and culture in Los Angeles. Lynda then interviews Branden one-on-one, and they talk about Brandens beginnings, most notable projects, and where he sees himself and technology headed in the future." },
                        { category_id: 2, name: "iOS SDK Essential Training (2012)", description: "In this course, author Simon Allardice shows how to develop, debug, and deploy applications for the Apple iPhone, iPad, and iPod touch using iOS 5 SDK and Xcode 4. The course reviews Objective-C basics, covers key concepts such as the Model-View-Controller pattern and delegation, and explores new features of the SDK, including Automatic Reference Counting (ARC) and Storyboards. The course also shows how to create and customize user interfaces and table views and develop apps with multiple view controllers, and explores the differences between iPhone and iPad development. Exercise files accompany the course." },
                        { category_id: 2, name: "Managing a Hosted Web Site", description: "Managing a Hosted Web Site shows how to set up a web site on a hosts server and perform common server tasks. Working in two web hosting utilities, cPanel and Plesk, as well as in a custom control panel, author Ray Villalobos explores purchasing a domain, setting up FTP accounts, and configuring web mail. The course also explains setting up password protection, creating a MySQL database, and working with subdomains. Exercise files accompany the course." },
                        { category_id: 2, name: "MVC Frameworks for Building PHP Web Applications", description: "In this course, author Drew Falkman tours four open-source PHP frameworks: Zend, Symfony, CakePHP, and CodeIgniter. The course covers basic framework concepts; explores the Model-View-Controller (MVC) pattern as a means of simplifying, organizing, and maintaining code; and details the ins and outs of developing basic applications in each of the four frameworks. Exercise files accompany the course." },
                        { category_id: 2, name: "Up and Running with Java Applications", description: "This course spotlights the R13 update for MAXON CINEMA 4D, which includes some key improvements in the rendering, shader, and character tools. Author Rob Garrott shows animators how to find their way around the interface, and demonstrates features such as the Physical Render engine, with its camera and depth of field and motion blur controls; the CMotion system for creating parametric movement; and the new and revised shaders. The course also covers the streamlined workflow for Adobe After Effects Exchange and the new file format options OpenEXR and Xref. Exercise files are included with the course." },
                        { category_id: 2, name: "Accessing the Titanium", description: "This course is an introduction to developing Java applications for various runtime environments. Author Todd Perkins explains how to configure the development environment, connect a web application to a MySQL database, and build a user interface with the Swing framework. The course also covers publishing applets in a web browser, working with XML data, and creating apps for Android devices. Exercise files accompany the course." },
                        { category_id: 2, name: "Titanium Mobile App Development Essential Training", description: "n this course, author Rafael Hernandez shows how to create native iOS and Android applications from a single codebase with the open-source Appcelerator Titanium platform. The course explains the difference between browser-based JavaScript and Titanium JavaScript, shows how to create a basic application, and demonstrates building buttons, sliders, switches, and pickers. The course also covers creating tables, implementing maps, providing feedback to users, incorporating multimedia, detecting gestures, and preparing finished apps for distribution. Exercise files accompany the course." },
                        ])

(1..20).each do |n|
  lessons = Lesson.create(name: "lesson#{n}", course_id: n/2+1)
  (1..2).each do |k|
    testings = Testing.create(name: "test #{k}", lesson_id: n)
  end
end




